import type { Metadata } from "next";
import "./globals.css";
import AuthGuard from "./components/AuthGuard";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
  <link
    href="https://fonts.googleapis.com/icon?family=Material+Icons"
    rel="stylesheet"
  />
</head>

      <body
      >
        <AuthGuard>
          {children}
        </AuthGuard>

      </body>
    </html>
  );
}
