// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Softools.Auth;

#nullable disable

namespace Softools.Auth.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20250816130157_AddRoles")]
    partial class AddRoles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Softools.Auth.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0198b2f8-f42e-7fb7-a46f-457d2738099b"),
                            Name = "Presidente"
                        },
                        new
                        {
                            Id = new Guid("0198b2f8-f42e-7533-9bbe-ad7ae49cf19a"),
                            Name = "Diretor"
                        },
                        new
                        {
                            Id = new Guid("0198b2f8-f42e-77f1-abad-3784e1e6401e"),
                            Name = "Projetos"
                        },
                        new
                        {
                            Id = new Guid("0198b2f8-f42e-7ff3-92d7-e0e105eafd39"),
                            Name = "RH"
                        },
                        new
                        {
                            Id = new Guid("0198b2f8-f42e-78aa-90ea-0ffc405e98ce"),
                            Name = "Financeiro"
                        },
                        new
                        {
                            Id = new Guid("0198b2f8-f42e-7ce0-a796-4f7aa7f82849"),
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = new Guid("0198b2f8-f42e-736b-948e-380bd1c25618"),
                            Name = "Comercial"
                        });
                });

            modelBuilder.Entity("Softools.Auth.Entities.UserCredentials", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("UserCredentials");
                });

            modelBuilder.Entity("Softools.Auth.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Softools.Auth.Entities.UserRole", b =>
                {
                    b.HasOne("Softools.Auth.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Softools.Auth.Entities.UserCredentials", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Softools.Auth.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Softools.Auth.Entities.UserCredentials", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
